version: '3.9'

services:
  user-service:
    build: ./user-service
    ports:
      - "8081:8081"

  product-service:
    build: ./product-service
    ports:
      - "8082:8082"

  order-service:
    build: ./order-service
    ports:
      - "8083:8083"

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - product-service
      - order-service
